### ISSUE TITLE
Boba Drops Tutorial is Not Obvious

### ISSUE THREAD

**Issue by JaredSene** [hackclub/boba-drops#9]
The beginner tutorial on the Boba Drops page is hidden behind a link that says "by yourself". Many leaders I have spoken to did not know there was a tutorial linked on the page because it isn't obvious and easily missed. This can lower engagement among clubs and beginners since they often can't find a beginner friendly way of learning how to make a website and earn the Boba Tea grant.

The beginner tutorial link on the Boba page should be more obvious by saying 'tutorial' or presenting the link similarly to how Hackaccino's page does.

**Comment by WolfGamer2** [comment]
![Image](https://github.com/user-attachments/assets/fe44652c-8c93-4572-9619-fe42f319ffb5)

**Comment by WolfGamer2** [comment]
@JaredSene  This should be fixed now!
